from fastapi import FastAPI, UploadFile, File, Request
from fastapi.responses import FileResponse, RedirectResponse
from fastapi.templating import Jinja2Templates
from fpdf import FPDF
import requests
import re
import os
import json
import sqlite3
import uuid
from datetime import datetime

app = FastAPI()
templates = Jinja2Templates(directory="templates")

# FOLDER MANAGEMENT
REPORT_DIR = "static/reports"
if not os.path.exists(REPORT_DIR):
    os.makedirs(REPORT_DIR)

# DATABASE SETUP 
def init_db():
    conn = sqlite3.connect('scans.db')
    cursor = conn.cursor()
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS scans (
            id TEXT PRIMARY KEY,
            timestamp TEXT,
            filename TEXT,
            results_json TEXT
        )
    ''')
    conn.commit()
    conn.close()

init_db()

# PDF GENERATOR
class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 15, 'SentryVault Security Audit Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated by SentryVault Engine v3.5 - Page {self.page_no()}', 0, 0, 'C')

#UTILS
def get_risk_score(vulns):
    if not vulns: return "Safe"
    for v in vulns:
        if "critical" in str(v).lower(): return "Critical"
    return "Moderate"

def scan_pkg(name, version, ecosystem):
    # Display logic for missing versions
    display_version = version if (version and version != "0.0.0") else "Not Specified in your file"
    search_version = version if (version and version != "0.0.0") else "0.0.0"

    url = "https://api.osv.dev/v1/query"
    payload = {"version": search_version, "package": {"name": name, "ecosystem": ecosystem}}
    try:
        res = requests.post(url, json=payload, timeout=10)
        if res.status_code == 200:
            data = res.json()
            vulns = data.get("vulns", [])
            risk = get_risk_score(vulns)
            fix_cmd = f"pip install {name} --upgrade" if ecosystem == "PyPI" else f"npm install {name}@latest"
            return {
                "name": name, "version": display_version, 
                "risk": risk, "count": len(vulns), "type": ecosystem, 
                "fix": fix_cmd if len(vulns) > 0 else "Verified Safe"
            }
    except: return None
    return None

# ROUTES
@app.get("/")
async def home(request: Request):
    conn = sqlite3.connect('scans.db')
    cursor = conn.cursor()
    cursor.execute("SELECT id, timestamp, filename FROM scans ORDER BY timestamp DESC")
    history = cursor.fetchall()
    conn.close()
    return templates.TemplateResponse("index.html", {"request": request, "results": None, "history": history})

@app.post("/scan")
async def scan_file(request: Request, file: UploadFile = File(...)):
    filename = file.filename
    content = await file.read()
    results = []
    
    if filename.endswith(".txt"):
        lines = content.decode("utf-8").splitlines()
        for line in lines:
            line = line.strip()
            if not line or line.startswith("#"): continue
            match = re.match(r"([a-zA-Z0-9\-_]+)(==|>=|<=|>|<)?([0-9\.]+)?", line)
            if match:
                pkg_name = match.group(1)
                pkg_ver = match.group(3) if match.group(3) else "0.0.0"
                res = scan_pkg(pkg_name, pkg_ver, "PyPI")
                if res: results.append(res)

    elif filename.endswith(".json"):
        try:
            data = json.loads(content.decode("utf-8"))
            deps = {**data.get("dependencies", {}), **data.get("devDependencies", {})}
            for name, ver in deps.items():
                clean_ver = re.sub(r'[\^~>=<]', '', str(ver))
                res = scan_pkg(name, clean_ver if clean_ver else "0.0.0", "npm")
                if res: results.append(res)
        except: pass

    scan_id = str(uuid.uuid4())[:8]
    conn = sqlite3.connect('scans.db')
    cursor = conn.cursor()
    cursor.execute("INSERT INTO scans VALUES (?, ?, ?, ?)", 
                   (scan_id, datetime.now().strftime("%Y-%m-%d %H:%M"), filename, json.dumps(results)))
    conn.commit()
    conn.close()
    return RedirectResponse(url=f"/view/{scan_id}", status_code=303)

@app.get("/view/{scan_id}")
async def view_scan(request: Request, scan_id: str):
    conn = sqlite3.connect('scans.db')
    cursor = conn.cursor()
    cursor.execute("SELECT results_json, filename FROM scans WHERE id=?", (scan_id,))
    row = cursor.fetchone()
    cursor.execute("SELECT id, timestamp, filename FROM scans ORDER BY timestamp DESC")
    history = cursor.fetchall()
    conn.close()
    if row:
        return templates.TemplateResponse("index.html", {
            "request": request, "results": json.loads(row[0]), 
            "current_file": row[1], "history": history, "scan_id": scan_id
        })
    return RedirectResponse(url="/")

@app.get("/download/{scan_id}")
async def download_pdf(scan_id: str):
    conn = sqlite3.connect('scans.db')
    cursor = conn.cursor()
    cursor.execute("SELECT results_json, filename FROM scans WHERE id=?", (scan_id,))
    row = cursor.fetchone()
    conn.close()

    if not row: return {"error": "Scan not found"}
    results, original_filename = json.loads(row[0]), row[1]

    pdf = PDFReport()
    pdf.add_page()
    
    # Header Info
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(0, 8, f"Source File: {original_filename}", 0, 1)
    pdf.set_font("Arial", '', 10)
    pdf.cell(0, 8, f"Scan Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1)
    pdf.ln(5)

    # Table Header
    pdf.set_font("Arial", 'B', 10)
    pdf.set_fill_color(30, 41, 59) # Dark Blue/Slate
    pdf.set_text_color(255, 255, 255)
    pdf.cell(60, 12, " Library Identity", 1, 0, 'L', 1)
    pdf.cell(35, 12, " Risk Status", 1, 0, 'C', 1)
    pdf.cell(95, 12, " Remediation Path", 1, 1, 'L', 1)
    
    # Table Content
    pdf.set_font("Arial", '', 9)
    pdf.set_text_color(0, 0, 0)
    
    for item in results:
        # Risk color logic for PDF
        if item['risk'] == 'Critical':
            pdf.set_text_color(220, 38, 38) # Red
        elif item['risk'] == 'Moderate':
            pdf.set_text_color(217, 119, 6) # Amber
        else:
            pdf.set_text_color(5, 150, 105) # Green
            
        name_display = f"{item['name']} ({item['version'][:25]})"
        pdf.cell(60, 10, f" {name_display}", 1, 0, 'L')
        pdf.cell(35, 10, f" {item['risk'].upper()}", 1, 0, 'C')
        
        pdf.set_text_color(30, 41, 59)
        fix_text = item['fix'] if item['count'] > 0 else "Verified Safe"
        pdf.cell(95, 10, f" {fix_text[:55]}", 1, 1, 'L')

    report_path = os.path.join(REPORT_DIR, f"report_{scan_id}.pdf")
    pdf.output(report_path)
    return FileResponse(report_path, filename=f"SentryVault_Audit_{scan_id}.pdf")
